defaults:
  - /trainer/basetrainer@_here_ # specialize the basetrainer!
  - _self_

trainerobj:
  _target_: masif.trainer.sh_scheduler.SHScheduler
  optimizer:
    _partial_: true
    _target_: torch.optim.Adam
    lr: 0.001
  sh_config:
    eta: 2
    budgets: ${dataset.slices}

