_target_: masif.models.masif_wp.masif_WP

encoder:
  _target_: masif.utils.mlp.MLP
  hidden_dims:
    - ${ dynamically_computed.n_data_meta_features }
    - 300
    - 200
  #  [ ${ dynamically_computed.n_data_meta_features }, 200, 100 ]
  activation: 'relu'

decoder:
  _target_: masif.utils.mlp.MLP
  hidden_dims:
    - 200
    - ${dynamically_computed.n_algos}

  #  [ ${ add: ${ model.encoder.mlp_dims[ 0 ] }, ${ transformer_dims[ 0 ] } }, 200, 100 ] # fixme: change index
  activation: 'relu'

input_dim: ${dynamically_computed.n_algos}
n_layers: 2
device: 'cpu'


