# @package _global_

defaults:
  - train_test_split: trainvalfixedtest # trainvalidtest #leave_one_out
  - dataset: lcbench
  - trainer: basetrainer
  - _self_

# placeholder for attributes to be computed
dynamically_computed:
  n_algos: None
  n_datasets: None
  n_data_meta_features: None
  n_algo_meta_features: None
  n_fidelities: None


seed: 0
output_dir: ./tmp

num_workers: 2
device: cpu #${device_ident:None} # FIXME: debug that all tensors are on same device with cuda


wandb:
  id: null
  entity:
  project: masif
  mode: 'offline'    # Change to offline or debug mode
  job_type: train
  tags: [ ]
  notes: null
  group: null
  sync_tensorboard: False
  save_code: False
  resume: 'allow'

hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}

# Directory structure
root: ${hydra:runtime.cwd}
dir_data: ${root}/data
dir_data_raw: ${dir_data}/raw
dir_data_processed: ${dir_data}/preprocessed

# saving models specification
#save_models: False # Fixme: currently disabled
#save_path: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}_${dataset.name}_${model.name}_${seed}
