_target_: masif.data.Dataset_LC
path: ${dataset.path.lc_meta}

# the important part!
transforms:
  _target_: masif.data.preprocessings.transformpipeline.TransformPipeline
  modulelist:
    - _target_: masif.data.preprocessings.nan_transforms.Column_Mean
    # - _target_: masif.data.preprocessings.table_transforms.Scalar
    - _target_: masif.data.preprocessings.lc_slice.LC_TimeSlices
      slices: [ 51 ]
    # - _target_: masif.data.preprocessings.tensor_transforms.LossScalar

metric: ${dataset.lc_metric}
